# Generated by Django 5.0.3 on 2024-04-18 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funko_api', '0006_platform_remove_tienda_games_game_tienda_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='operativeSistem',
            new_name='Platform',
        ),
    ]
