# Generated by Django 5.0.3 on 2024-04-25 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funko_api', '0008_rename_platform_game_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='game',
            name='tienda',
        ),
        migrations.RemoveField(
            model_name='gamer',
            name='games',
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.DeleteModel(
            name='Tienda',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Gamer',
        ),
    ]
