# Generated by Django 5.0.3 on 2024-05-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funko_api', '0010_game_gamedeveloper_gamestore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedeveloper',
            name='games',
        ),
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.ManyToManyField(to='funko_api.gamedeveloper'),
        ),
    ]
