# Generated by Django 5.0.3 on 2024-05-23 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funko_api', '0012_remove_gamestore_developer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='gamestore',
            name='games',
        ),
        migrations.DeleteModel(
            name='GameDeveloper',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='GameStore',
        ),
    ]
