# Generated by Django 5.0.3 on 2024-05-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestore',
            name='games',
        ),
        migrations.AddField(
            model_name='game',
            name='store',
            field=models.ManyToManyField(to='games_api.gamestore'),
        ),
    ]
